#include <stdio.h>
#include "object.h"
#include "toggle.h"
static const char *tags0[] = { "field", NULL};
static const char *tags1[] = { "cave", NULL};
static const char *tags2[] = { "copse", NULL};
static const char *tags3[] = { "silver", "coin", "silver coin", NULL};
static const char *tags4[] = { "gold", "coin", "gold coin", NULL};
static const char *tags5[] = { "sword", "basic sword", NULL};
static const char *tags6[] = { "axe", "battle axe", NULL};
static const char *tags7[] = { "yourself", NULL};
static const char *tags8[] = { "guard", "royal guard", NULL};
static const char *tags9[] = { "skeleton", "guard", "skeleton guard", NULL};
static const char *tags10[] = { "witch", "evil witch", NULL};
static const char *tags11[] = { "south", "exit", "leave", NULL};
static const char *tags12[] = { "north", "entrance", NULL};
static int condition13(OBJECT *obj)  { return guard->health <= 0 || silver->location == guard; }
static const char *tags13[] = { "east", "entrance", NULL};
static int condition14(OBJECT *obj)  { return guard->health > 0 && silver->location != guard; }
static const char *tags14[] = { "east", "entrance", NULL};
static const char *tags15[] = { "west", "out", NULL};
static const char *tags16[] = { "west", "north", "south", "forest", NULL};
static const char *tags17[] = { "east", "north", "rock", NULL};
static const char *tags18[] = { "backroom", NULL};
static const char *tags19[] = { "east", "west", "south", "rock", NULL};
static const char *tags20[] = { "passageway", NULL};
static const char *tags21[] = { "passageway", NULL};
static const char *tags22[] = { "north", "south", "rock", NULL};
static const char *tags23[] = { "east", NULL};
static const char *tags24[] = { "chamber", NULL};
static const char *tags25[] = { "east", "entrance", "chamber", "enter", NULL};
static const char *tags26[] = { "east", "exit", "leave", NULL};
static const char *tags27[] = { "chamberStaircase", NULL};
static int condition28(OBJECT *obj)  { return skeletonGuard->health <= 0; }
static const char *tags28[] = { "north", "staircase", "chamberStaircase", "old staircase", NULL};
static int condition29(OBJECT *obj)  { return skeletonGuard->health > 0; }
static const char *tags29[] = { "north", "staircase", "chamberStaircase", NULL};
static const char *tags30[] = { "south", "chamber", NULL};
static const char *tags31[] = { "vaults", "centralVaults", NULL};
static const char *tags32[] = { "east", "vaults", "chamberStaircase", NULL};
static const char *tags33[] = { "west", "staircase", "chamberStaircase", NULL};
static const char *tags34[] = { "witches lair", "lair", NULL};
static const char *tags35[] = { "north", "door", "doorway", NULL};
static const char *tags36[] = { "north", "door", "doorway", "witches door", NULL};
static const char *tags37[] = { "south", "door", "doorway", NULL};
static const char *tags38[] = { "west", "door", "doorway", NULL};
static const char *tags39[] = { "torture chamber", "centralVaults", NULL};
static const char *tags40[] = { "south", "chamber", "tortureChamber", NULL};
static const char *tags41[] = { "north", "vaults", "central vaults", NULL};
static const char *tags42[] = { "torture chamber", "centralVaults", NULL};
static int condition43(OBJECT *obj)  { return torch -> lit == 0 && torch -> location == player->location; }
static const char *tags43[] = { "east", "deeper", "deep", NULL};
static int condition44(OBJECT *obj)  { return torch->lit == 1; }
static const char *tags44[] = { "east", "deeper", "deep", NULL};
static const char *tags45[] = { "west", "vaults", "central vaults", NULL};
static const char *tags46[] = { "chamberAnteroom", "anteroom", NULL};
static int condition47(OBJECT *obj)  { return skeletonGuard -> health <= 0; }
static const char *tags47[] = { "south", "anteroom", "chamberAnteroom", NULL};
static int condition48(OBJECT *obj)  { return skeletonGuard -> health > 0; }
static const char *tags48[] = { "south", "anteroom", "chamberAnteroom", NULL};
static const char *tags49[] = { "north", "exit", "leave", "exit anteroom", NULL};
static const char *tags50[] = { "chamberAnteroom", "anteroom", NULL};
static const char *tags51[] = { "east", "door", "doorway", "library door", NULL};
static const char *tags52[] = { "east", "door", "doorway", "library door", NULL};
static const char *tags53[] = { "west", "door", "doorway", "library door", NULL};
static const char *tags54[] = { "west", "door", "doorway", NULL};
static const char *tags55[] = { "south", "door", "doorway", NULL};
static const char *tags56[] = { "south", "door", "doorway", NULL};
static const char *tags57[] = { "north", "door", "doorway", NULL};
static const char *tags58[] = { "north", "door", "doorway", NULL};
static const char *tags59[] = { "box", "wooden box", NULL};
static const char *tags60[] = { "box", "wooden box", NULL};
static const char *tags61[] = { "box", "wooden box", NULL};
static const char *tags62[] = { "key", "tiny key", NULL};
static const char *tags63[] = { "key", "old key", "iron key", "old iron key", NULL};
static const char *tags64[] = { "torch", "unlit torch", NULL};
static const char *tags65[] = { "cauldron", "bubbling cauldron", NULL};
static const char *tags66[] = { "book", "demon book", "grimoire", "ars goetia", NULL};

static int alwaysTrue(OBJECT *obj) { return 1; }

OBJECT objs[] = {
	{	/* 0 = field */
		alwaysTrue,
		 "an open field",
		tags0,
		NULL,
		NULL,
		NULL,
		 "The field is a nice and quiet place under a clear blue sky.\n A royal guard is protecting the entrance to the cave, I wonder what's in there",
		"You see",
		"You can't get any closer than this.\n",
		99,
		9999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 1 = cave */
		alwaysTrue,
		 "a little cave",
		tags1,
		NULL,
		NULL,
		NULL,
		 "The cave is just a cold, damp, rocky chamber.\n",
		"You see",
		"You can't get any closer than this.\n",
		99,
		9999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 2 = copse */
		alwaysTrue,
		 "a small wooded copse",
		tags2,
		NULL,
		NULL,
		NULL,
		 "A small copse surrounded by shrubs. The remains of a fallen knight lay on the floor\n",
		"You see",
		"You can't get any closer than this.\n",
		99,
		9999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 3 = silver */
		alwaysTrue,
		 "a silver coin",
		tags3,
		 field,
		NULL,
		NULL,
		 "The coin has an eagle on the obverse.\n",
		"You see",
		"You can't get any closer than this.\n",
		 1,
		9999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 4 = gold */
		alwaysTrue,
		 "a gold coin",
		tags4,
		 openBox,
		NULL,
		NULL,
		 "The shiny coin seems to be a rare and priceless artefact.\n",
		"You see",
		"You can't get any closer than this.\n",
		 1,
		9999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 5 = sword */
		alwaysTrue,
		 "a basic sword",
		tags5,
		 copse,
		NULL,
		NULL,
		 "A simple sword for protection.\n",
		"You see",
		"You can't get any closer than this.\n",
		 1,
		9999,
		0,
		 5,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 6 = axe */
		alwaysTrue,
		 "a battle axe",
		tags6,
		 tortureChamber,
		NULL,
		NULL,
		 "A axe designed for combat. There is dried blood on the blade\n",
		"You see",
		"You can't get any closer than this.\n",
		 3,
		9999,
		0,
		 8,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 7 = player */
		alwaysTrue,
		 "yourself",
		tags7,
		 copse,
		NULL,
		NULL,
		 "You would need a mirror to look at yourself.\n",
		 "You have",
		"You can't get any closer than this.\n",
		99,
		 20,
		 100,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 8 = guard */
		alwaysTrue,
		 "a royal guard",
		tags8,
		 field,
		NULL,
		NULL,
		 "The guard is protecting the entrance to the cave, I wonder why?\n",
		 "He has",
		"You can't get any closer than this.\n",
		99,
		 20,
		 10,
		 2,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 9 = skeletonGuard */
		alwaysTrue,
		 "an necromanced skeleton guard",
		tags9,
		 chamber,
		NULL,
		NULL,
		 "The skeleton is blocking the way through the chamber.\n There must be a necromancer nearby",
		 "He has",
		"You can't get any closer than this.\n",
		99,
		 20,
		 15,
		 10,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 10 = evilWitch */
		alwaysTrue,
		 "An evil witch guarding the cauldron. She looks frail, I reckon she'll go down with one swing of an axe. Don't let her hit you!",
		tags10,
		 witchesLair,
		NULL,
		NULL,
		 "The witch is guarding the cauldron. She looks dangerous\n",
		 "She has",
		"You can't get any closer than this.\n",
		99,
		 20,
		 8,
		 50,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 11 = exitCopse */
		alwaysTrue,
		 "a field to the south",
		tags11,
		 copse,
		 field,
		 field,
		 "The copse has a field next to the south\n",
		"You see",
		 "You exit the copse to the field\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 12 = intoCopse */
		alwaysTrue,
		 "a small copse to the north",
		tags12,
		 field,
		 copse,
		 copse,
		 "The field has a small copse on one side\n",
		"You see",
		 "You walk across the field to the copse\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 13 = intoCave */
		condition13,
		 "a cave entrance to the east",
		tags13,
		 field,
		 cave,
		 cave,
		 "The entrance is just a narrow opening in a small outcrop.\n",
		"You see",
		 "You walk into the cave.\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 14 = intoCaveBlocked */
		condition14,
		 "a large cave entrance to the east",
		tags14,
		 field,
		NULL,
		 cave,
		 "The entrance looks well worn, people have used this to get somewhere.\n",
		"You see",
		 "The royal guard stops you from walking into the cave. Maybe I can bribe him, or use a blade\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 15 = exitCave */
		alwaysTrue,
		 "a way out to the west",
		tags15,
		 cave,
		 field,
		 field,
		 "Sunlight pours in through the entrance in the cave's wall.\n",
		"You see",
		 "You walk out of the cave.\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 16 = wallField */
		alwaysTrue,
		 "a thick, dense forest all around",
		tags16,
		 field,
		NULL,
		NULL,
		 "The field is surrounded by trees and undergrowth.\n",
		"You see",
		 "Dense forest is blocking the way.\n",
		99,
		9999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 17 = wallCave */
		alwaysTrue,
		 "solid rock all around",
		tags17,
		 cave,
		NULL,
		NULL,
		 "Carved in stone is a secret password 'abccb'.\n",
		"You see",
		 "Solid rock is blocking the way.\n",
		99,
		9999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 18 = backroom */
		alwaysTrue,
		 "a manmade backroom built into the cave",
		tags18,
		NULL,
		NULL,
		NULL,
		 "The room is dusty and messy. There is mysterious writing on the walls\n",
		"You see",
		"You can't get any closer than this.\n",
		99,
		9999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 19 = wallBackroom */
		alwaysTrue,
		 "solid rock all around",
		tags19,
		 backroom,
		NULL,
		NULL,
		 "The rock walls are cold and damp. There is mysterious writing scribbled on the walls\n",
		"You see",
		 "Solid rock is blocking the way.\n",
		99,
		9999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 20 = passageway */
		alwaysTrue,
		 "a narrow passageway. It's cramped in here",
		tags20,
		NULL,
		NULL,
		NULL,
		 "The passageway is narrow and dimly lit.\n",
		"You see",
		"You can't get any closer than this.\n",
		99,
		9999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 21 = intoPassageway */
		alwaysTrue,
		 "a narrow passageway to the west",
		tags21,
		 backroom,
		 passageway,
		 passageway,
		 "The backroom has a small passageway\n",
		"You see",
		 "You walk into the narrow passageway.\n OH NO! The walls have caved in behind you.\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 22 = wallPassageway */
		alwaysTrue,
		 "damp walls",
		tags22,
		 passageway,
		NULL,
		NULL,
		 "The rock walls are cold and damp.\n",
		"You see",
		 "Solid rock is blocking the way.\n",
		99,
		9999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 23 = wallChamber */
		alwaysTrue,
		 "cold stone walls covered in blood",
		tags23,
		 chamber,
		NULL,
		NULL,
		 "The stone walls are splattered with blood.\n",
		"You see",
		 "Solid stone walls are blocking the way\n",
		99,
		9999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 24 = chamber */
		alwaysTrue,
		 "a large chamber, the room smells of death and decay",
		tags24,
		NULL,
		NULL,
		NULL,
		 "The chamber is eerily quiet. Is that blood on the floor and walls?\n",
		"You see",
		"You can't get any closer than this.\n",
		99,
		9999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 25 = intoChamber */
		alwaysTrue,
		 "an opening to a large gothic chamber to the east",
		tags25,
		 passageway,
		 chamber,
		 chamber,
		 "The passageway opens up to a large gothic chamber\n",
		"You see",
		 "You climb into the large gothic chamber. There is an uneasy presence in the air\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 26 = exitChamber */
		alwaysTrue,
		 "a small passageway to the east",
		tags26,
		 chamber,
		 passageway,
		 passageway,
		 "There is a narrow passageway at the entrance to the chamber\n",
		"You see",
		 "You exit chamber into the narrow passageway\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 27 = chamberStaircase */
		alwaysTrue,
		 "a staircase to the north side of the chamber",
		tags27,
		NULL,
		NULL,
		NULL,
		 "The staircase leads up out of the chamber \n",
		"You see",
		"You can't get any closer than this.\n",
		99,
		9999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 28 = intoChamberStaircase */
		condition28,
		 "a old staircase leading downwards to the north",
		tags28,
		 chamber,
		 chamberStaircase,
		 chamberStaircase,
		 "The staircase leads deeper down\n",
		"You see",
		 "You walk into the staircase to the north of the chamber\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 29 = intoChamberStaircaseBlocked */
		condition29,
		 "a old staircase leading downwards to the north",
		tags29,
		 chamber,
		NULL,
		 chamberStaircase,
		 "The staircase leads deeper down\n",
		"You see",
		 "You cannot get passed the skeleton guard\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 30 = exitChamberStaircase */
		alwaysTrue,
		 "a large chamber at the top of the staircase to the south",
		tags30,
		 chamberStaircase,
		 chamber,
		 chamber,
		 "There is large chamber at the top of the staircase\n",
		"You see",
		 "You climb the staircase and go to the chamber\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 31 = centralVaults */
		alwaysTrue,
		 "dark and dingy vaults. You can barely see a thing",
		tags31,
		NULL,
		NULL,
		NULL,
		 "The bottom of the staircase leads to the vaults\n",
		"You see",
		"You can't get any closer than this.\n",
		99,
		9999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 32 = intoCentralVaults */
		alwaysTrue,
		 "an opening to some vaults at the bottom of the staircase to the east",
		tags32,
		 chamberStaircase,
		 centralVaults,
		 centralVaults,
		 "The staircase leads deeper down\n",
		"You see",
		 "You walk into the staircase\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 33 = exitCentralVaultsStaircase */
		alwaysTrue,
		 "a staircase leading back the the chamber to the west",
		tags33,
		 centralVaults,
		NULL,
		 chamberStaircase,
		 "The staircase leads back to the chamber\n",
		"You see",
		 "You go to the chamber staircase\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 34 = witchesLair */
		alwaysTrue,
		 "the evil witches lair. \nThere are potions and spellbooks everywhere\n",
		tags34,
		NULL,
		NULL,
		NULL,
		 "There is a bubbling cauldron over a FIRE protected by an evil witch \\n",
		"You see",
		"You can't get any closer than this.\n",
		99,
		9999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 35 = openDoorToWitchesLair */
		alwaysTrue,
		 "a rusty metal door to the north. You hear cackling from inside",
		tags35,
		NULL,
		 witchesLair,
		 witchesLair,
		 "The door is open.\n",
		"You see",
		 "You walk through the door into the witches lair.\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		 toggleWitchesLairDoor,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 36 = closedDoorToWitchesLair */
		alwaysTrue,
		 "a rusty metal door to the north. It's closed. There are mystical drawings around the door",
		tags36,
		 centralVaults,
		NULL,
		 witchesLair,
		 "The door is closed.\n",
		"You see",
		 "The door is closed.\n",
		99,
		9999,
		0,
		0,
		 toggleWitchesLairDoor,
		 isAlreadyClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 37 = openDoorToCentralVaults */
		alwaysTrue,
		 "a rusty metal door to the south leading to the central vaults. It's open",
		tags37,
		NULL,
		 centralVaults,
		 centralVaults,
		 "The door is open.\n",
		"You see",
		 "You walk through the rusty metal door to the vaults\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		 toggleWitchesLairDoor,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 38 = closedDoorToCentralVaults */
		alwaysTrue,
		 "an ornate wooden door to the west leading to the chamber anteroom. It's open",
		tags38,
		 witchesLair,
		NULL,
		 centralVaults,
		 "The door is closed.\n",
		"You see",
		 "The door is closed.\n",
		99,
		9999,
		0,
		0,
		 toggleWitchesLairDoor,
		 isAlreadyClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 39 = tortureChamber */
		alwaysTrue,
		 "a small chamber filled with torture equipment",
		tags39,
		NULL,
		NULL,
		NULL,
		 "The bottom of the staircase leads to the vaults\n",
		"You see",
		"You can't get any closer than this.\n",
		99,
		9999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 40 = intoTortureChamber */
		alwaysTrue,
		 "an archway leading to the torture chamber to the south",
		tags40,
		 centralVaults,
		 tortureChamber,
		 tortureChamber,
		 "The torture chamber is filled with bloody torture tools\n",
		"You see",
		 "You head into the torture chamber\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 41 = exitTortureChamber */
		alwaysTrue,
		 "an archway leading to the central vaults to the north",
		tags41,
		 tortureChamber,
		 centralVaults,
		 centralVaults,
		 "The archway leads out of the torture chamber back to the vaults\n",
		"You see",
		 "You go to the central vaults\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 42 = deepCentralVaults */
		alwaysTrue,
		 "a deeper and darker section of the central vaults",
		tags42,
		NULL,
		NULL,
		NULL,
		 "The bottom of the staircase leads to the vaults\n",
		"You see",
		"You can't get any closer than this.\n",
		99,
		9999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 43 = intoDeepCentralVaults */
		condition43,
		 "a deeper section of the central vaults to the east",
		tags43,
		 centralVaults,
		 deepCentralVaults,
		 deepCentralVaults,
		 "The vaults are pitch black\n",
		"You see",
		 "You head into the deeper section of the vaults\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 44 = intoDeepCentralVaultsBlocked */
		condition44,
		 "a deeper section of the central vaults to the east",
		tags44,
		 centralVaults,
		NULL,
		 deepCentralVaults,
		 "The vaults are pitch black\n",
		"You see",
		 "it's too dark to go any further without a light source\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 45 = exitDeepCentralVaults */
		alwaysTrue,
		 "the vaults get brighter to the west",
		tags45,
		 deepCentralVaults,
		NULL,
		 centralVaults,
		 "The vaults get lighter east heading to the staircase\n",
		"You see",
		 "You go to the central vaults\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 46 = chamberAnteroom */
		alwaysTrue,
		 "a small anteroom to the south of the chamber",
		tags46,
		NULL,
		NULL,
		NULL,
		 "The anteroom the backs onto the chamber \n",
		"You see",
		"You can't get any closer than this.\n",
		99,
		9999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 47 = intoChamberAnteroom */
		condition47,
		 "an small anteroom to the south",
		tags47,
		 chamber,
		 chamberAnteroom,
		 chamberAnteroom,
		 "The anteroom is covered in dust",
		"You see",
		 "You walk into the chamber's anteroom \n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 48 = intoChamberAnteroomBlocked */
		condition48,
		 "an small anteroom to the south",
		tags48,
		 chamber,
		NULL,
		 chamberAnteroom,
		 "The anteroom is covered in dust",
		"You see",
		 "You cannot get past the skeleton guard \n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 49 = exitChamberAnteroom */
		alwaysTrue,
		 "a large chamber to the north",
		tags49,
		 chamberAnteroom,
		 chamber,
		 chamber,
		 "There is a large entrance to the chamber\n",
		"You see",
		 "You exit anteroom into the chamber\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 50 = library */
		alwaysTrue,
		 "a creepy looking libary room",
		tags50,
		NULL,
		NULL,
		NULL,
		 "The books in this library look strange, it's unusually cold in here \n",
		"You see",
		"You can't get any closer than this.\n",
		99,
		9999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 51 = openDoorToLibrary */
		alwaysTrue,
		 "an ornate wooden door to the east. It's open",
		tags51,
		NULL,
		 library,
		 library,
		 "The door is open.\n",
		"You see",
		 "You walk through the door into the library.\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		 toggleBackdoor,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 52 = closedDoorToLibrary */
		alwaysTrue,
		 "an ornate wooden door to the east. It's closed",
		tags52,
		 chamberAnteroom,
		NULL,
		 library,
		 "The door is closed.\n",
		"You see",
		 "The door is closed.\n",
		99,
		9999,
		0,
		0,
		 toggleLibaryDoor,
		 isAlreadyClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 53 = openDoorToAnteroom */
		alwaysTrue,
		 "an ornate wooden door to the west leading to the chamber anteroom. It's open",
		tags53,
		NULL,
		 chamberAnteroom,
		 chamberAnteroom,
		 "The door is open.\n",
		"You see",
		 "You walk through the door into the chamber anteroom\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		 toggleLibaryDoor,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 54 = closedDoorToAnteroom */
		alwaysTrue,
		 "An ornate wooden door to the west leading to the chamber anteroom. It's open",
		tags54,
		 library,
		NULL,
		 chamberAnteroom,
		 "The door is closed.\n",
		"You see",
		 "The door is closed.\n",
		99,
		9999,
		0,
		0,
		 toggleLibaryDoor,
		 isAlreadyClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 55 = openDoorToBackroom */
		alwaysTrue,
		 "an open door to the south",
		tags55,
		NULL,
		 backroom,
		 backroom,
		 "The door is open.\n",
		"You see",
		 "You walk through the door into the backroom.\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		 toggleLibaryDoor,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 56 = closedDoorToBackroom */
		alwaysTrue,
		 "a closed door to the south",
		tags56,
		 cave,
		NULL,
		 backroom,
		 "The door is closed.\n",
		"You see",
		 "The door is closed.\n",
		99,
		9999,
		0,
		0,
		 toggleBackdoor,
		 isAlreadyClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 57 = openDoorToCave */
		alwaysTrue,
		 "an open door to the north",
		tags57,
		NULL,
		 cave,
		 cave,
		 "The door is open.\n",
		"You see",
		 "You walk through the door into the cave.\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		 toggleBackdoor,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 58 = closedDoorToCave */
		alwaysTrue,
		 "a closed door to the north",
		tags58,
		 backroom,
		NULL,
		 cave,
		 "The door is closed.\n",
		"You see",
		 "The door is closed.\n",
		99,
		9999,
		0,
		0,
		 toggleBackdoor,
		 isAlreadyClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 59 = openBox */
		alwaysTrue,
		 "a wooden box",
		tags59,
		NULL,
		NULL,
		NULL,
		 "The box is open.\n",
		"You see",
		"You can't get any closer than this.\n",
		 5,
		 10,
		0,
		0,
		 isAlreadyOpen,
		 toggleBox,
		 isStillOpen,
		 isAlreadyOpen,
		0
	},
	{	/* 60 = closedBox */
		alwaysTrue,
		 "a wooden box",
		tags60,
		NULL,
		NULL,
		NULL,
		 "The box is closed.\n",
		"You see",
		"You can't get any closer than this.\n",
		 5,
		9999,
		0,
		0,
		 toggleBox,
		 isAlreadyClosed,
		 toggleBoxLock,
		 isAlreadyUnlocked,
		0
	},
	{	/* 61 = lockedBox */
		alwaysTrue,
		 "a wooden box",
		tags61,
		 backroom,
		NULL,
		NULL,
		 "The box is closed.\n",
		"You see",
		"You can't get any closer than this.\n",
		 5,
		9999,
		0,
		0,
		 isStillLocked,
		 isAlreadyClosed,
		 isAlreadyLocked,
		 toggleBoxLock,
		0
	},
	{	/* 62 = keyForBox */
		alwaysTrue,
		 "a tiny key",
		tags62,
		 cave,
		NULL,
		NULL,
		 "The key is really small and shiny.\n",
		"You see",
		"You can't get any closer than this.\n",
		 1,
		9999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 63 = oldIronKey */
		alwaysTrue,
		 "an old iron key",
		tags63,
		 tortureChamber,
		NULL,
		NULL,
		 "The key old and rusty. Perhaps someone was chained up with this\n",
		"You see",
		"You can't get any closer than this.\n",
		 1,
		9999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 64 = torch */
		alwaysTrue,
		 "an unlit torch",
		tags64,
		 centralVaults,
		NULL,
		NULL,
		 "The torch is unlit. Maybe I can find a way to light it up",
		"You see",
		"You can't get any closer than this.\n",
		 1,
		9999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		 1
	},
	{	/* 65 = cauldron */
		alwaysTrue,
		 "a bubbling cauldron",
		tags65,
		 witchesLair,
		NULL,
		NULL,
		 "The cauldron is bubbling with a fire underneath",
		"You see",
		"You can't get any closer than this.\n",
		 999,
		9999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 66 = bookArsGoetia */
		alwaysTrue,
		 "the ars goetia, a grimoire book on demonology",
		tags66,
		 library,
		NULL,
		NULL,
		 "This book appears to be grimoire. \n",
		"You see",
		"You can't get any closer than this.\n",
		 1,
		9999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	}
};
