#include <stdio.h>
#include "object.h"
#include "toggle.h"
static const char *tags0[] = { "field", NULL};
static const char *tags1[] = { "cave", NULL};
static const char *tags2[] = { "copse", NULL};
static const char *tags3[] = { "silver", "coin", "silver coin", NULL};
static const char *tags4[] = { "gold", "coin", "gold coin", NULL};
static const char *tags5[] = { "sword", "basic sword", NULL};
static const char *tags6[] = { "axe", "battle axe", NULL};
static const char *tags7[] = { "yourself", NULL};
static const char *tags8[] = { "guard", "royal guard", NULL};
static const char *tags9[] = { "skeleton", "guard", "skeleton guard", NULL};
static const char *tags10[] = { "witch", "evil witch", NULL};
static const char *tags11[] = { "warden", "demon warden", NULL};
static const char *tags12[] = { "south", "exit", "leave", NULL};
static const char *tags13[] = { "north", "entrance", NULL};
static int condition14(OBJECT *obj)  { return guard->health <= 0 || silver->location == guard; }
static const char *tags14[] = { "east", "entrance", NULL};
static int condition15(OBJECT *obj)  { return guard->health > 0 && silver->location != guard; }
static const char *tags15[] = { "east", "entrance", NULL};
static const char *tags16[] = { "west", "out", NULL};
static const char *tags17[] = { "west", "north", "south", "forest", NULL};
static const char *tags18[] = { "east", "north", "rock", NULL};
static const char *tags19[] = { "backroom", NULL};
static const char *tags20[] = { "east", "west", "south", "rock", NULL};
static const char *tags21[] = { "passageway", NULL};
static const char *tags22[] = { "passageway", NULL};
static const char *tags23[] = { "north", "south", "rock", NULL};
static const char *tags24[] = { "east", NULL};
static const char *tags25[] = { "chamber", NULL};
static const char *tags26[] = { "east", "entrance", "chamber", "enter", NULL};
static const char *tags27[] = { "east", "exit", "leave", NULL};
static const char *tags28[] = { "chamberStaircase", NULL};
static int condition29(OBJECT *obj)  { return skeletonGuard->health <= 0; }
static const char *tags29[] = { "north", "staircase", "chamberStaircase", "old staircase", NULL};
static int condition30(OBJECT *obj)  { return skeletonGuard->health > 0; }
static const char *tags30[] = { "north", "staircase", "chamberStaircase", NULL};
static const char *tags31[] = { "south", "chamber", NULL};
static const char *tags32[] = { "vaults", "centralVaults", NULL};
static const char *tags33[] = { "east", "vaults", "chamberStaircase", NULL};
static const char *tags34[] = { "west", "staircase", "chamberStaircase", NULL};
static const char *tags35[] = { "witches lair", "lair", NULL};
static const char *tags36[] = { "north", "door", "doorway", NULL};
static const char *tags37[] = { "north", "door", "doorway", "witches door", NULL};
static const char *tags38[] = { "south", "door", "doorway", NULL};
static const char *tags39[] = { "west", "door", "doorway", NULL};
static const char *tags40[] = { "torture chamber", "centralVaults", NULL};
static const char *tags41[] = { "south", "chamber", "tortureChamber", NULL};
static const char *tags42[] = { "north", "vaults", "central vaults", NULL};
static const char *tags43[] = { "torture chamber", "centralVaults", NULL};
static int condition44(OBJECT *obj)  { return torch -> lit == 0; }
static const char *tags44[] = { "east", "deeper", "deep", NULL};
static int condition45(OBJECT *obj)  { return torch->lit == 1; }
static const char *tags45[] = { "east", "deeper", "deep", NULL};
static const char *tags46[] = { "west", "vaults", "central vaults", NULL};
static const char *tags47[] = { "body pit", "pit", NULL};
static const char *tags48[] = { "north", "pit", "body pit", NULL};
static const char *tags49[] = { "south", "vaults", "deep", NULL};
static const char *tags50[] = { "ladder", NULL};
static const char *tags51[] = { "east", "ladder", NULL};
static const char *tags52[] = { "west", "vaults", "up", NULL};
static const char *tags53[] = { "catacombsEast", NULL};
static const char *tags54[] = { "catacombsNorthEast", NULL};
static const char *tags55[] = { "north", "catacombs north", NULL};
static const char *tags56[] = { "south", "catacombs south", NULL};
static const char *tags57[] = { "catacombsSouthEast", NULL};
static const char *tags58[] = { "north", "catacombs south", NULL};
static const char *tags59[] = { "south", "catacombs south", NULL};
static const char *tags60[] = { "catacombsCentral", NULL};
static const char *tags61[] = { "west", "catacombs west", NULL};
static const char *tags62[] = { "east", "catacombs east", NULL};
static const char *tags63[] = { "catacombsNorth", NULL};
static const char *tags64[] = { "east", "catacombs east", NULL};
static const char *tags65[] = { "west", "catacombs west", NULL};
static const char *tags66[] = { "south", "catacombs sotuh", NULL};
static const char *tags67[] = { "north", "catacombs north", NULL};
static const char *tags68[] = { "catacombsSouth", NULL};
static const char *tags69[] = { "east", "catacombs east", NULL};
static const char *tags70[] = { "west", "catacombs west", NULL};
static const char *tags71[] = { "north", "catacombs north", NULL};
static const char *tags72[] = { "west", "catacombs west", NULL};
static const char *tags73[] = { "catacombsSouthWest", NULL};
static const char *tags74[] = { "west", "catacombs west", NULL};
static const char *tags75[] = { "east", "catacombs east", NULL};
static const char *tags76[] = { "catacombsNorthWest", NULL};
static const char *tags77[] = { "north", "catacombs north", NULL};
static const char *tags78[] = { "east", "catacombs east", NULL};
static const char *tags79[] = { "catacombsWest", NULL};
static const char *tags80[] = { "south", "catacombs south", NULL};
static const char *tags81[] = { "north", "catacombs north", NULL};
static const char *tags82[] = { "north", "catacombs north", NULL};
static const char *tags83[] = { "south", "catacombs south", NULL};
static const char *tags84[] = { "east", "catacombs east", NULL};
static const char *tags85[] = { "west", "catacombs west", NULL};
static const char *tags86[] = { "north", "catacombs north", NULL};
static const char *tags87[] = { "south", "catacombs south", NULL};
static const char *tags88[] = { "west", "catacombs west", NULL};
static const char *tags89[] = { "west", "ladder", NULL};
static const char *tags90[] = { "crypt", "forbidden crypt", NULL};
static const char *tags91[] = { "east", "crypt", "forbidden crypt", NULL};
static const char *tags92[] = { "west", "catacombs", "catacombs west", NULL};
static const char *tags93[] = { "room", "chamber", "chamber of rest", NULL};
static const char *tags94[] = { "south", "chamber", NULL};
static const char *tags95[] = { "north", "catacombs", "catacombs north", NULL};
static const char *tags96[] = { "sewer", "hole", "sewer entrance", NULL};
static const char *tags97[] = { "gate", "door", "sewer gate", NULL};
static const char *tags98[] = { "gate", "door", "sewer gate", NULL};
static const char *tags99[] = { "gate", "sewer gate", "catatcombs", NULL};
static const char *tags100[] = { "gate", "sewer gate", "catatcombs", NULL};
static const char *tags101[] = { "guardRoom", NULL};
static const char *tags102[] = { "south", "door", "doorway", "guard room door", NULL};
static const char *tags103[] = { "south", "door", "doorway", "guard room door", NULL};
static const char *tags104[] = { "north", "door", "doorway", "vault door", NULL};
static const char *tags105[] = { "north", "door", "doorway", "vault door", NULL};
static const char *tags106[] = { "office", "wardens office", NULL};
static const char *tags107[] = { "south", "office", "wardens office", NULL};
static const char *tags108[] = { "north", "guard room", NULL};
static const char *tags109[] = { "chamberAnteroom", "anteroom", NULL};
static int condition110(OBJECT *obj)  { return skeletonGuard -> health <= 0; }
static const char *tags110[] = { "south", "anteroom", "chamberAnteroom", NULL};
static int condition111(OBJECT *obj)  { return skeletonGuard -> health > 0; }
static const char *tags111[] = { "south", "anteroom", "chamberAnteroom", NULL};
static const char *tags112[] = { "north", "exit", "leave", "exit anteroom", NULL};
static const char *tags113[] = { "chamberAnteroom", "anteroom", NULL};
static const char *tags114[] = { "east", "door", "doorway", "library door", NULL};
static const char *tags115[] = { "east", "door", "doorway", "library door", NULL};
static const char *tags116[] = { "west", "door", "doorway", "library door", NULL};
static const char *tags117[] = { "west", "door", "doorway", NULL};
static const char *tags118[] = { "south", "door", "doorway", NULL};
static const char *tags119[] = { "south", "door", "doorway", NULL};
static const char *tags120[] = { "north", "door", "doorway", NULL};
static const char *tags121[] = { "north", "door", "doorway", NULL};
static const char *tags122[] = { "box", "wooden box", NULL};
static const char *tags123[] = { "box", "wooden box", NULL};
static const char *tags124[] = { "box", "wooden box", NULL};
static const char *tags125[] = { "chest", "iron chest", NULL};
static const char *tags126[] = { "chest", "iron chest", NULL};
static const char *tags127[] = { "chest", "iron chest", NULL};
static const char *tags128[] = { "key", "bloody key", "iron key", NULL};
static const char *tags129[] = { "key", "tiny key", NULL};
static const char *tags130[] = { "key", "small key", NULL};
static const char *tags131[] = { "torch", "unlit torch", NULL};
static const char *tags132[] = { "cauldron", "bubbling cauldron", NULL};
static const char *tags133[] = { "corpse", "stiched corpse", "body", NULL};
static const char *tags134[] = { "corpse", "stiched corpse", "body", NULL};
static const char *tags135[] = { "book", "demon book", "grimoire", "ars goetia", NULL};
static const char *tags136[] = { "book", "demon book", "grimoire", "ars theurgia goetia", NULL};

static int alwaysTrue(OBJECT *obj) { return 1; }

OBJECT objs[] = {
	{	/* 0 = field */
		alwaysTrue,
		 "an open field",
		tags0,
		NULL,
		NULL,
		NULL,
		 "The field is a nice and quiet place under a clear blue sky.\n A royal guard is protecting the entrance to the cave, I wonder what's in there",
		"You see",
		"You can't get any closer than this.\n",
		99,
		9999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 1 = cave */
		alwaysTrue,
		 "a little cave",
		tags1,
		NULL,
		NULL,
		NULL,
		 "The cave is just a cold, damp, rocky chamber.\n",
		"You see",
		"You can't get any closer than this.\n",
		99,
		9999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 2 = copse */
		alwaysTrue,
		 "a small wooded copse",
		tags2,
		NULL,
		NULL,
		NULL,
		 "A small copse surrounded by shrubs. The remains of a fallen knight lay on the floor\n",
		"You see",
		"You can't get any closer than this.\n",
		99,
		9999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 3 = silver */
		alwaysTrue,
		 "a silver coin",
		tags3,
		 field,
		NULL,
		NULL,
		 "The coin has an eagle on the obverse.\n",
		"You see",
		"You can't get any closer than this.\n",
		 1,
		9999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 4 = gold */
		alwaysTrue,
		 "a gold coin",
		tags4,
		 openBox,
		NULL,
		NULL,
		 "The shiny coin seems to be a rare and priceless artefact.\n",
		"You see",
		"You can't get any closer than this.\n",
		 1,
		9999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 5 = sword */
		alwaysTrue,
		 "a basic sword",
		tags5,
		 copse,
		NULL,
		NULL,
		 "A simple sword for protection.\n",
		"You see",
		"You can't get any closer than this.\n",
		 1,
		9999,
		0,
		 5,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 6 = axe */
		alwaysTrue,
		 "a battle axe",
		tags6,
		 tortureChamber,
		NULL,
		NULL,
		 "A axe designed for combat. There is dried blood on the blade\n",
		"You see",
		"You can't get any closer than this.\n",
		 3,
		9999,
		0,
		 8,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 7 = player */
		alwaysTrue,
		 "yourself",
		tags7,
		 catacombsWest,
		NULL,
		NULL,
		 "You would need a mirror to look at yourself.\n",
		 "You have",
		"You can't get any closer than this.\n",
		99,
		 20,
		 100,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 8 = guard */
		alwaysTrue,
		 "a royal guard",
		tags8,
		 field,
		NULL,
		NULL,
		 "The guard is protecting the entrance to the cave, I wonder why?\n",
		 "He has",
		"You can't get any closer than this.\n",
		99,
		 20,
		 10,
		 2,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 9 = skeletonGuard */
		alwaysTrue,
		 "a necromanced skeleton guard",
		tags9,
		 chamber,
		NULL,
		NULL,
		 "The skeleton is blocking the way through the chamber.\n There must be a necromancer nearby",
		 "He has",
		"You can't get any closer than this.\n",
		99,
		 20,
		 15,
		 10,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 10 = evilWitch */
		alwaysTrue,
		 "An evil witch guarding the cauldron. She looks frail, I reckon she'll go down with one swing of an axe. Don't let her hit you!",
		tags10,
		 witchesLair,
		NULL,
		NULL,
		 "The witch is guarding the cauldron. She looks dangerous\n",
		 "She has",
		"You can't get any closer than this.\n",
		99,
		 20,
		 8,
		 50,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 11 = demonWarden */
		alwaysTrue,
		 "The warden has turned into a demon. It's feasting on a body in the corner and hasn't noticed you",
		tags11,
		 wardensOffice,
		NULL,
		NULL,
		 "The demon looks dazed. It has giant claws and teeth ready to tear flesh\n",
		 "It has",
		"You can't get any closer than this.\n",
		99,
		 20,
		 20,
		 60,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 12 = exitCopse */
		alwaysTrue,
		 "a field to the south",
		tags12,
		 copse,
		 field,
		 field,
		 "The copse has a field next to the south\n",
		"You see",
		 "You exit the copse to the field\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 13 = intoCopse */
		alwaysTrue,
		 "a small copse to the north",
		tags13,
		 field,
		 copse,
		 copse,
		 "The field has a small copse on one side\n",
		"You see",
		 "You walk across the field to the copse\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 14 = intoCave */
		condition14,
		 "a cave entrance to the east",
		tags14,
		 field,
		 cave,
		 cave,
		 "The entrance is just a narrow opening in a small outcrop.\n",
		"You see",
		 "You walk into the cave.\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 15 = intoCaveBlocked */
		condition15,
		 "a large cave entrance to the east",
		tags15,
		 field,
		NULL,
		 cave,
		 "The entrance looks well worn, people have used this to get somewhere.\n",
		"You see",
		 "The royal guard stops you from walking into the cave. Maybe I can bribe him, or use a blade\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 16 = exitCave */
		alwaysTrue,
		 "a way out to the west",
		tags16,
		 cave,
		 field,
		 field,
		 "Sunlight pours in through the entrance in the cave's wall.\n",
		"You see",
		 "You walk out of the cave.\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 17 = wallField */
		alwaysTrue,
		 "a thick, dense forest all around",
		tags17,
		 field,
		NULL,
		NULL,
		 "The field is surrounded by trees and undergrowth.\n",
		"You see",
		 "Dense forest is blocking the way.\n",
		99,
		9999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 18 = wallCave */
		alwaysTrue,
		 "solid rock all around",
		tags18,
		 cave,
		NULL,
		NULL,
		 "Carved in stone is a secret password 'abccb'.\n",
		"You see",
		 "Solid rock is blocking the way.\n",
		99,
		9999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 19 = backroom */
		alwaysTrue,
		 "a manmade backroom built into the cave",
		tags19,
		NULL,
		NULL,
		NULL,
		 "The room is dusty and messy. There is mysterious writing on the walls\n",
		"You see",
		"You can't get any closer than this.\n",
		99,
		9999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 20 = wallBackroom */
		alwaysTrue,
		 "solid rock all around",
		tags20,
		 backroom,
		NULL,
		NULL,
		 "The rock walls are cold and damp. There is mysterious writing scribbled on the walls\n",
		"You see",
		 "Solid rock is blocking the way.\n",
		99,
		9999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 21 = passageway */
		alwaysTrue,
		 "a narrow passageway. It's cramped in here",
		tags21,
		NULL,
		NULL,
		NULL,
		 "The passageway is narrow and dimly lit.\n",
		"You see",
		"You can't get any closer than this.\n",
		99,
		9999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 22 = intoPassageway */
		alwaysTrue,
		 "a narrow passageway to the west",
		tags22,
		 backroom,
		 passageway,
		 passageway,
		 "The backroom has a small passageway\n",
		"You see",
		 "You walk into the narrow passageway.\n OH NO! The walls have caved in behind you.\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 23 = wallPassageway */
		alwaysTrue,
		 "damp walls",
		tags23,
		 passageway,
		NULL,
		NULL,
		 "The rock walls are cold and damp.\n",
		"You see",
		 "Solid rock is blocking the way.\n",
		99,
		9999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 24 = wallChamber */
		alwaysTrue,
		 "cold stone walls covered in blood",
		tags24,
		 chamber,
		NULL,
		NULL,
		 "The stone walls are splattered with blood.\n",
		"You see",
		 "Solid stone walls are blocking the way\n",
		99,
		9999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 25 = chamber */
		alwaysTrue,
		 "a large chamber, the room smells of death and decay",
		tags25,
		NULL,
		NULL,
		NULL,
		 "The chamber is eerily quiet. Is that blood on the floor and walls?\n",
		"You see",
		"You can't get any closer than this.\n",
		99,
		9999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 26 = intoChamber */
		alwaysTrue,
		 "an opening to a large gothic chamber to the east",
		tags26,
		 passageway,
		 chamber,
		 chamber,
		 "The passageway opens up to a large gothic chamber\n",
		"You see",
		 "You climb into the large gothic chamber. There is an uneasy presence in the air\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 27 = exitChamber */
		alwaysTrue,
		 "a small passageway to the east",
		tags27,
		 chamber,
		 passageway,
		 passageway,
		 "There is a narrow passageway at the entrance to the chamber\n",
		"You see",
		 "You exit chamber into the narrow passageway\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 28 = chamberStaircase */
		alwaysTrue,
		 "a staircase to the north side of the chamber",
		tags28,
		NULL,
		NULL,
		NULL,
		 "The staircase leads up out of the chamber \n",
		"You see",
		"You can't get any closer than this.\n",
		99,
		9999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 29 = intoChamberStaircase */
		condition29,
		 "a old staircase leading downwards to the north",
		tags29,
		 chamber,
		 chamberStaircase,
		 chamberStaircase,
		 "The staircase leads deeper down\n",
		"You see",
		 "You walk into the staircase to the north of the chamber\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 30 = intoChamberStaircaseBlocked */
		condition30,
		 "a old staircase leading downwards to the north",
		tags30,
		 chamber,
		NULL,
		 chamberStaircase,
		 "The staircase leads deeper down\n",
		"You see",
		 "You cannot get passed the skeleton guard\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 31 = exitChamberStaircase */
		alwaysTrue,
		 "a large chamber at the top of the staircase to the south",
		tags31,
		 chamberStaircase,
		 chamber,
		 chamber,
		 "There is large chamber at the top of the staircase\n",
		"You see",
		 "You climb the staircase and go to the chamber\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 32 = centralVaults */
		alwaysTrue,
		 "dark and dingy vaults. You can barely see a thing",
		tags32,
		NULL,
		NULL,
		NULL,
		 "The bottom of the staircase leads to the vaults\n",
		"You see",
		"You can't get any closer than this.\n",
		99,
		9999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 33 = intoCentralVaults */
		alwaysTrue,
		 "an opening to some vaults at the bottom of the staircase to the east",
		tags33,
		 chamberStaircase,
		 centralVaults,
		 centralVaults,
		 "The staircase leads deeper down\n",
		"You see",
		 "You walk into the staircase\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 34 = exitCentralVaultsStaircase */
		alwaysTrue,
		 "a staircase leading back the the chamber to the west",
		tags34,
		 centralVaults,
		NULL,
		 chamberStaircase,
		 "The staircase leads back to the chamber\n",
		"You see",
		 "You go to the chamber staircase\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 35 = witchesLair */
		alwaysTrue,
		 "the evil witches lair. \nThere are potions and spellbooks everywhere\n",
		tags35,
		NULL,
		NULL,
		NULL,
		 "There is a bubbling cauldron over a FIRE protected by an evil witch \\n",
		"You see",
		"You can't get any closer than this.\n",
		99,
		9999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 36 = openDoorToWitchesLair */
		alwaysTrue,
		 "a rusty metal door to the north. You hear cackling from inside",
		tags36,
		NULL,
		 witchesLair,
		 witchesLair,
		 "The door is open.\n",
		"You see",
		 "You walk through the door into the witches lair.\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		 toggleWitchesLairDoor,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 37 = closedDoorToWitchesLair */
		alwaysTrue,
		 "a rusty metal door to the north. It's closed. There are mystical drawings around the door",
		tags37,
		 centralVaults,
		NULL,
		 witchesLair,
		 "The door is closed.\n",
		"You see",
		 "The door is closed.\n",
		99,
		9999,
		0,
		0,
		 toggleWitchesLairDoor,
		 isAlreadyClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 38 = openDoorToCentralVaults */
		alwaysTrue,
		 "a rusty metal door to the south leading to the central vaults. It's open",
		tags38,
		NULL,
		 centralVaults,
		 centralVaults,
		 "The door is open.\n",
		"You see",
		 "You walk through the rusty metal door to the vaults\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		 toggleWitchesLairDoor,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 39 = closedDoorToCentralVaults */
		alwaysTrue,
		 "an ornate wooden door to the west leading to the chamber anteroom. It's open",
		tags39,
		 witchesLair,
		NULL,
		 centralVaults,
		 "The door is closed.\n",
		"You see",
		 "The door is closed.\n",
		99,
		9999,
		0,
		0,
		 toggleWitchesLairDoor,
		 isAlreadyClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 40 = tortureChamber */
		alwaysTrue,
		 "a small chamber filled with torture equipment",
		tags40,
		NULL,
		NULL,
		NULL,
		 "The bottom of the staircase leads to the vaults\n",
		"You see",
		"You can't get any closer than this.\n",
		99,
		9999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 41 = intoTortureChamber */
		alwaysTrue,
		 "an archway leading to the torture chamber to the south",
		tags41,
		 centralVaults,
		 tortureChamber,
		 tortureChamber,
		 "The torture chamber is filled with bloody torture tools\n",
		"You see",
		 "You head into the torture chamber\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 42 = exitTortureChamber */
		alwaysTrue,
		 "an archway leading to the central vaults to the north",
		tags42,
		 tortureChamber,
		 centralVaults,
		 centralVaults,
		 "The archway leads out of the torture chamber back to the vaults\n",
		"You see",
		 "You go to the central vaults\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 43 = deepCentralVaults */
		alwaysTrue,
		 "a deeper and darker section of the central vaults",
		tags43,
		NULL,
		NULL,
		NULL,
		 "The bottom of the staircase leads to the vaults\n",
		"You see",
		"You can't get any closer than this.\n",
		99,
		9999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 44 = intoDeepCentralVaults */
		condition44,
		 "a deeper section of the central vaults to the east",
		tags44,
		 centralVaults,
		 deepCentralVaults,
		 deepCentralVaults,
		 "The vaults are pitch black\n",
		"You see",
		 "You head into the deeper section of the vaults\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 45 = intoDeepCentralVaultsBlocked */
		condition45,
		 "a deeper section of the central vaults to the east",
		tags45,
		 centralVaults,
		NULL,
		 deepCentralVaults,
		 "The vaults are pitch black\n",
		"You see",
		 "it's too dark to go any further without a light source\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 46 = exitDeepCentralVaults */
		alwaysTrue,
		 "the vaults get brighter to the west",
		tags46,
		 deepCentralVaults,
		NULL,
		 centralVaults,
		 "The vaults get lighter east heading to the staircase\n",
		"You see",
		 "You go to the central vaults\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 47 = bodyPit */
		alwaysTrue,
		 "a large pit of rotting corpses",
		tags47,
		NULL,
		NULL,
		NULL,
		 "The bodies appear to have been tortured ritually. Who would do such a thing?\n",
		"You see",
		"You can't get any closer than this.\n",
		99,
		9999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 48 = intoBodyPit */
		alwaysTrue,
		 "a vile stench is coming from the north",
		tags48,
		 deepCentralVaults,
		 bodyPit,
		 bodyPit,
		 "The place reeks of rotting corpses.\n",
		"You see",
		 "You head north following the wretched stench\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 49 = exitBodyPit */
		alwaysTrue,
		 "the deep vaults are to the south",
		tags49,
		 bodyPit,
		 deepCentralVaults,
		 deepCentralVaults,
		 "The dark vaults are south of here\n",
		"You see",
		 "You go to the deep vaults \n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 50 = ladderRoom */
		alwaysTrue,
		 "A ladder between the vaults and the cathedral",
		tags50,
		NULL,
		NULL,
		NULL,
		 "The bodies appear to have been tortured ritually. Who would do such a thing?\n",
		"You see",
		"You can't get any closer than this.\n",
		99,
		9999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 51 = intoladderRoom */
		alwaysTrue,
		 "a ladder leading even deeper to the east",
		tags51,
		 deepCentralVaults,
		 ladderRoom,
		 ladderRoom,
		 "The ladder goes down deeper into the earth\n",
		"You see",
		 "You head east and start climbing down the ladder\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 52 = exitladderRoomVaults */
		alwaysTrue,
		 "the deep vaults at the top of the ladder on the west side",
		tags52,
		 ladderRoom,
		 deepCentralVaults,
		 deepCentralVaults,
		 "The ladder is creeking as you use it",
		"You see",
		 "You climb the ladder into the vaults\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 53 = catacombsEast */
		alwaysTrue,
		 "A web of deep tunnels filled with resting places for the dead",
		tags53,
		NULL,
		NULL,
		NULL,
		 "The is space for more bodies here. Can I hear footsteps?\n",
		"You see",
		"You can't get any closer than this.\n",
		99,
		9999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 54 = catacombsNorthEast */
		alwaysTrue,
		 "A web of deep tunnels filled with resting places for the dead",
		tags54,
		NULL,
		NULL,
		NULL,
		 "The is space for more bodies here. There is something else in here.\n",
		"You see",
		"You can't get any closer than this.\n",
		99,
		9999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 55 = intoCatacombsNorthEast */
		alwaysTrue,
		 "more catacombs to the north",
		tags55,
		 catacombsEast,
		 catacombsNorthEast,
		 catacombsNorthEast,
		 "The catacombs extend to the north\n",
		"You see",
		 "You head north through the ancient catacombs\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 56 = exitCatacombsNorthEastToEast */
		alwaysTrue,
		 "more catacombs to the south",
		tags56,
		 catacombsNorthEast,
		 catacombsEast,
		 catacombsEast,
		 "The catacombs extend to the south",
		"You see",
		 "You head south through the catacombs\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 57 = catacombsSouthEast */
		alwaysTrue,
		 "A web of deep tunnels filled with resting places for the dead",
		tags57,
		NULL,
		NULL,
		NULL,
		 "The is space for more bodies here. There is something else in here.\n",
		"You see",
		"You can't get any closer than this.\n",
		99,
		9999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 58 = intoCatacombsSouthEastFromEast */
		alwaysTrue,
		 "more catacombs to the south",
		tags58,
		 catacombsEast,
		 catacombsSouthEast,
		 catacombsSouthEast,
		 "The catacombs extend to the south\n",
		"You see",
		 "You head south through the ancient catacombs\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 59 = exitCatacombsSouthEastToEast */
		alwaysTrue,
		 "more catacombs to the south",
		tags59,
		 catacombsSouthEast,
		 catacombsEast,
		 catacombsEast,
		 "The catacombs extend to the north",
		"You see",
		 "You head north through the catacombs\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 60 = catacombsCentral */
		alwaysTrue,
		 "A web of deep tunnels filled with resting places for the dead",
		tags60,
		NULL,
		NULL,
		NULL,
		 "The is space for more bodies here. There is something else in here.\n",
		"You see",
		"You can't get any closer than this.\n",
		99,
		9999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 61 = intoCatacombsCentralFromEast */
		alwaysTrue,
		 "more catacombs to the west",
		tags61,
		 catacombsEast,
		 catacombsCentral,
		 catacombsCentral,
		 "The catacombs extend to the west\n",
		"You see",
		 "You head west through the ancient catacombs\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 62 = exitCatacombsCentralToEast */
		alwaysTrue,
		 "more catacombs to the east",
		tags62,
		 catacombsCentral,
		 catacombsEast,
		 catacombsEast,
		 "The catacombs extend to the east",
		"You see",
		 "You head east through the catacombs\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 63 = catacombsNorth */
		alwaysTrue,
		 "A web of deep tunnels filled with resting places for the dead",
		tags63,
		NULL,
		NULL,
		NULL,
		 "The is space for more bodies here. There is an uneasy presence.\n",
		"You see",
		"You can't get any closer than this.\n",
		99,
		9999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 64 = intoCatacombsNorthFromNorthEast */
		alwaysTrue,
		 "more catacombs to the east",
		tags64,
		 catacombsNorthEast,
		 catacombsNorth,
		 catacombsNorth,
		 "The catacombs extend to the east\n",
		"You see",
		 "You head east through the ancient catacombs\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 65 = exitCatacombsNorthEastToNorth */
		alwaysTrue,
		 "more catacombs to the west",
		tags65,
		 catacombsNorth,
		 catacombsNorthEast,
		 catacombsNorthEast,
		 "The catacombs extend to the west",
		"You see",
		 "You head west through the catacombs\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 66 = intoCatacombsCentralFromNorth */
		alwaysTrue,
		 "more catacombs to the south",
		tags66,
		 catacombsNorth,
		 catacombsCentral,
		 catacombsCentral,
		 "The catacombs extend to the south\n",
		"You see",
		 "You head east through the ancient catacombs\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 67 = exitCatacombsNorthToNorthEast */
		alwaysTrue,
		 "more catacombs to the north",
		tags67,
		 catacombsNorth,
		 catacombsNorthEast,
		 catacombsNorthEast,
		 "The catacombs extend to the north",
		"You see",
		 "You head north through the catacombs\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 68 = catacombsSouth */
		alwaysTrue,
		 "A web of deep tunnels filled with resting places for the dead",
		tags68,
		NULL,
		NULL,
		NULL,
		 "The is space for more bodies here. There is an uneasy presence.\n",
		"You see",
		"You can't get any closer than this.\n",
		99,
		9999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 69 = intoCatacombsSouthFromSouthEast */
		alwaysTrue,
		 "more catacombs to the east",
		tags69,
		 catacombsSouthEast,
		 catacombsSouth,
		 catacombsSouth,
		 "The catacombs extend to the east\n",
		"You see",
		 "You head east through the ancient catacombs\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 70 = exitCatacombsSouthToSouthEast */
		alwaysTrue,
		 "more catacombs to the west",
		tags70,
		 catacombsSouth,
		 catacombsSouthEast,
		 catacombsSouthEast,
		 "The catacombs extend to the west",
		"You see",
		 "You head west through the catacombs\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 71 = intoCatacombsCentralFromSouth */
		alwaysTrue,
		 "more catacombs to the north",
		tags71,
		 catacombsSouth,
		 catacombsCentral,
		 catacombsCentral,
		 "The catacombs extend to the north\n",
		"You see",
		 "You head north through the ancient catacombs\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 72 = exitCatacombsSouthEastFromSouth */
		alwaysTrue,
		 "more catacombs to the west",
		tags72,
		 catacombsSouth,
		 catacombsSouthEast,
		 catacombsSouthEast,
		 "The catacombs extend to the west",
		"You see",
		 "You head west through the catacombs\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 73 = catacombsSouthWest */
		alwaysTrue,
		 "A web of deep tunnels filled with resting places for the dead",
		tags73,
		NULL,
		NULL,
		NULL,
		 "The is space for more bodies here. Is something following me?.\n",
		"You see",
		"You can't get any closer than this.\n",
		99,
		9999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 74 = intoCatacombsSouthWestFromSouth */
		alwaysTrue,
		 "more catacombs to the west",
		tags74,
		 catacombsSouth,
		 catacombsSouthWest,
		 catacombsSouthWest,
		 "The catacombs extend to the west\n",
		"You see",
		 "You head west through the ancient catacombs\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 75 = exitCatacombsSouthWestToSouth */
		alwaysTrue,
		 "more catacombs to the east",
		tags75,
		 catacombsSouthWest,
		 catacombsSouth,
		 catacombsSouth,
		 "The catacombs extend to the east",
		"You see",
		 "You head east through the catacombs\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 76 = catacombsNorthWest */
		alwaysTrue,
		 "A web of deep tunnels filled with resting places for the dead",
		tags76,
		NULL,
		NULL,
		NULL,
		 "The is space for more bodies here. Something smells like fresh blood\n",
		"You see",
		"You can't get any closer than this.\n",
		99,
		9999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 77 = intoCatacombsNorthWestFromNorth */
		alwaysTrue,
		 "more catacombs to the west",
		tags77,
		 catacombsNorth,
		 catacombsNorthWest,
		 catacombsNorthWest,
		 "The catacombs extend to the north\n",
		"You see",
		 "You head west through the ancient catacombs\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 78 = exitCatacombsNorthWestToNorth */
		alwaysTrue,
		 "more catacombs to the east",
		tags78,
		 catacombsNorthWest,
		 catacombsNorth,
		 catacombsNorth,
		 "The catacombs extend to the east",
		"You see",
		 "You head east through the catacombs\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 79 = catacombsWest */
		alwaysTrue,
		 "A web of deep tunnels filled with resting places for the dead",
		tags79,
		NULL,
		NULL,
		NULL,
		 "The is space for more bodies here. This place doesn't feel safe\n",
		"You see",
		"You can't get any closer than this.\n",
		99,
		9999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 80 = intoCatacombsWestFromNorthWest */
		alwaysTrue,
		 "more catacombs to the south",
		tags80,
		 catacombsNorthWest,
		 catacombsWest,
		 catacombsWest,
		 "The catacombs extend to the south\n",
		"You see",
		 "You head south through the ancient catacombs\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 81 = exitCatacombsWestToNorthWest */
		alwaysTrue,
		 "more catacombs to the north",
		tags81,
		 catacombsWest,
		 catacombsNorthWest,
		 catacombsNorthWest,
		 "The catacombs extend to the north",
		"You see",
		 "You head north through the catacombs\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 82 = intoCatacombsWestFromSouthWest */
		alwaysTrue,
		 "more catacombs to the north",
		tags82,
		 catacombsSouthWest,
		 catacombsWest,
		 catacombsWest,
		 "The catacombs extend to the north\n",
		"You see",
		 "You head north through the ancient catacombs\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 83 = exitCatacombsWestToSouthWest */
		alwaysTrue,
		 "more catacombs to the south",
		tags83,
		 catacombsWest,
		 catacombsSouthWest,
		 catacombsSouthWest,
		 "The catacombs extend to the south",
		"You see",
		 "You head south through the catacombs\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 84 = intoCatacombsCentralFromWest */
		alwaysTrue,
		 "more catacombs to the east",
		tags84,
		 catacombsWest,
		 catacombsCentral,
		 catacombsCentral,
		 "The catacombs extend to the east\n",
		"You see",
		 "You head east through the ancient catacombs\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 85 = exitCatacombsCentralToWest */
		alwaysTrue,
		 "more catacombs to the west",
		tags85,
		 catacombsCentral,
		 catacombsWest,
		 catacombsWest,
		 "The catacombs extend to the west",
		"You see",
		 "You head west through the catacombs\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 86 = exitCatacombsCentralToNorth */
		alwaysTrue,
		 "more catacombs to the north",
		tags86,
		 catacombsCentral,
		 catacombsNorth,
		 catacombsNorth,
		 "The catacombs extend to the north",
		"You see",
		 "You head north through the catacombs\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 87 = exitCatacombsCentralToSouth */
		alwaysTrue,
		 "more catacombs to the south",
		tags87,
		 catacombsCentral,
		 catacombsSouth,
		 catacombsSouth,
		 "The catacombs extend to the south",
		"You see",
		 "You head south through the catacombs\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 88 = intoCatacombsWest */
		alwaysTrue,
		 "an ancient web of catacombs to the east",
		tags88,
		 ladderRoom,
		 catacombsWest,
		 catacombsWest,
		 "The ladder leads to the catacombs\n",
		"You see",
		 "You head east and enter the ancient catacombs\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 89 = exitCatacombsWestLadder */
		alwaysTrue,
		 "the deep vaults at the top of the ladder on the west side",
		tags89,
		 catacombsWest,
		 ladderRoom,
		 ladderRoom,
		 "The ladder used to connect the vaults to the catacombs",
		"You see",
		 "You start climbing the ladder leading to the vaults\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 90 = forbiddenCrypt */
		alwaysTrue,
		 "A large crypt, possibly for an important person",
		tags90,
		NULL,
		NULL,
		NULL,
		 "The stone door has been smashed to pieces\n",
		"You see",
		"You can't get any closer than this.\n",
		99,
		9999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 91 = intoForbiddenCryptFromCatacombsEast */
		alwaysTrue,
		 "the forbidden crypt to the east",
		tags91,
		 catacombsEast,
		 forbiddenCrypt,
		 forbiddenCrypt,
		 "The forbidden crypt lies to the east\n",
		"You see",
		 "You head east into the forbidden crupt\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 92 = exitForbiddenCryptToCatacombsWest */
		alwaysTrue,
		 "the catacombs lie to the west",
		tags92,
		 forbiddenCrypt,
		 catacombsWest,
		 catacombsWest,
		 "The catacombsare to the west",
		"You see",
		 "You head west into the catacombs\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 93 = chamberOfRest */
		alwaysTrue,
		 "A small room, with a bed and chamber put",
		tags93,
		NULL,
		NULL,
		NULL,
		 "The stone door has been smashed to pieces\n",
		"You see",
		"You can't get any closer than this.\n",
		99,
		9999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 94 = intoChamberOfRestFromCatacombsSouth */
		alwaysTrue,
		 "the forbidden crypt to the west",
		tags94,
		 catacombsSouth,
		 chamberOfRest,
		 chamberOfRest,
		 "A small chamber lies to the south\n",
		"You see",
		 "You head south into the chamber\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 95 = exitChamberOfRestToCatacombsSouth */
		alwaysTrue,
		 "the catacombs lie to the north",
		tags95,
		 chamberOfRest,
		 catacombsSouth,
		 catacombsSouth,
		 "The catacombs lie to the north",
		"You see",
		 "You head north into the catacombs\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 96 = sewerEntrance */
		alwaysTrue,
		 "a hole leading down to some sewers",
		tags96,
		NULL,
		NULL,
		NULL,
		 "The room is filled with chains and torture devices\n",
		"You see",
		"You can't get any closer than this.\n",
		99,
		9999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 97 = openGateToSewerEntrance */
		alwaysTrue,
		 "a small gate, leading to a foul stench, it's open",
		tags97,
		NULL,
		 sewerEntrance,
		 sewerEntrance,
		 "The gate is open.\n",
		"You see",
		 "You walk through the gate into the sewers\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		 toggleGateToSewerEntrance,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 98 = closedGateToSewerEntrance */
		alwaysTrue,
		 "a small gate, leading to a foul stench, it's closed",
		tags98,
		 catacombsNorth,
		NULL,
		 sewerEntrance,
		 "The gate is closed.\n",
		"You see",
		 "The gate to the sewers is closed.\n",
		99,
		9999,
		0,
		0,
		 toggleGateToSewerEntrance,
		 isAlreadyClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 99 = openGateToCatacombsNorth */
		alwaysTrue,
		 "a small gate, leading to the catacombs, it's open",
		tags99,
		NULL,
		 catacombsNorth,
		 catacombsNorth,
		 "The gate is open.\n",
		"You see",
		 "You walk through the gate into the catacombs\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		 toggleGateToSewerEntrance,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 100 = closedGateToCatacombsNorth */
		alwaysTrue,
		 "a small gate, leading to the catacombs, it's closed",
		tags100,
		 sewerEntrance,
		NULL,
		 catacombsNorth,
		 "The gate is closed.\n",
		"You see",
		 "The gate to the sewers is closed.\n",
		99,
		9999,
		0,
		0,
		 toggleGateToSewerEntrance,
		 isAlreadyClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 101 = guardRoom */
		alwaysTrue,
		 "a room for the torturers to rest",
		tags101,
		NULL,
		NULL,
		NULL,
		 "The room is filled with chains and torture devices\n",
		"You see",
		"You can't get any closer than this.\n",
		99,
		9999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 102 = openDoorToGuardRoom */
		alwaysTrue,
		 "a iron door with 'guard room' enscribed on it to the south",
		tags102,
		NULL,
		 guardRoom,
		 guardRoom,
		 "The door is open.\n",
		"You see",
		 "You walk through the door into the guard room\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		 toggleGuardRoomDoor,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 103 = closedDoorToGuardRoom */
		alwaysTrue,
		 "a iron door with 'guard room' enscribed on it, it's closed",
		tags103,
		 deepCentralVaults,
		NULL,
		 guardRoom,
		 "The door is closed.\n",
		"You see",
		 "The door to the guard room is closed.\n",
		99,
		9999,
		0,
		0,
		 toggleGuardRoomDoor,
		 isAlreadyClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 104 = openDoorToDeepVaults */
		alwaysTrue,
		 "a iron door with 'To Vaults' enscribed on it",
		tags104,
		NULL,
		 deepCentralVaults,
		 deepCentralVaults,
		 "The door is open.\n",
		"You see",
		 "You walk through the door into the guard room\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		 toggleGuardRoomDoor,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 105 = closedDoorToDeepVaults */
		alwaysTrue,
		 "a iron door with 'To Vaults' enscribed on it, it's closed",
		tags105,
		 guardRoom,
		NULL,
		 deepCentralVaults,
		 "The door is closed.\n",
		"You see",
		 "The door to the deep vaults is closed.\n",
		99,
		9999,
		0,
		0,
		 toggleGuardRoomDoor,
		 isAlreadyClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 106 = wardensOffice */
		alwaysTrue,
		 "the Warden's office",
		tags106,
		NULL,
		NULL,
		NULL,
		 "The Warden must manage the operations from here. What were they trying to do?\n",
		"You see",
		"You can't get any closer than this.\n",
		99,
		9999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 107 = intoWardensOffice */
		alwaysTrue,
		 "a wardens office to the south",
		tags107,
		 guardRoom,
		 wardensOffice,
		 wardensOffice,
		 "The room has an ornate desk with a locked box on top\n",
		"You see",
		 "You head south into the warden's office\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 108 = exitWardenOffice */
		alwaysTrue,
		 "the deep vaults are to the south",
		tags108,
		 wardensOffice,
		 guardRoom,
		 guardRoom,
		 "The guard room is just north of here\n",
		"You see",
		 "You walk into the guard room \n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 109 = chamberAnteroom */
		alwaysTrue,
		 "a small anteroom to the south of the chamber",
		tags109,
		NULL,
		NULL,
		NULL,
		 "The anteroom the backs onto the chamber \n",
		"You see",
		"You can't get any closer than this.\n",
		99,
		9999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 110 = intoChamberAnteroom */
		condition110,
		 "an small anteroom to the south",
		tags110,
		 chamber,
		 chamberAnteroom,
		 chamberAnteroom,
		 "The anteroom is covered in dust",
		"You see",
		 "You walk into the chamber's anteroom \n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 111 = intoChamberAnteroomBlocked */
		condition111,
		 "an small anteroom to the south",
		tags111,
		 chamber,
		NULL,
		 chamberAnteroom,
		 "The anteroom is covered in dust",
		"You see",
		 "You cannot get past the skeleton guard \n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 112 = exitChamberAnteroom */
		alwaysTrue,
		 "a large chamber to the north",
		tags112,
		 chamberAnteroom,
		 chamber,
		 chamber,
		 "There is a large entrance to the chamber\n",
		"You see",
		 "You exit anteroom into the chamber\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 113 = library */
		alwaysTrue,
		 "a creepy looking libary room",
		tags113,
		NULL,
		NULL,
		NULL,
		 "The books in this library look strange, it's unusually cold in here \n",
		"You see",
		"You can't get any closer than this.\n",
		99,
		9999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 114 = openDoorToLibrary */
		alwaysTrue,
		 "an ornate wooden door to the east. It's open",
		tags114,
		NULL,
		 library,
		 library,
		 "The door is open.\n",
		"You see",
		 "You walk through the door into the library.\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		 toggleBackdoor,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 115 = closedDoorToLibrary */
		alwaysTrue,
		 "an ornate wooden door to the east. It's closed",
		tags115,
		 chamberAnteroom,
		NULL,
		 library,
		 "The door is closed.\n",
		"You see",
		 "The door is closed.\n",
		99,
		9999,
		0,
		0,
		 toggleLibaryDoor,
		 isAlreadyClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 116 = openDoorToAnteroom */
		alwaysTrue,
		 "an ornate wooden door to the west leading to the chamber anteroom. It's open",
		tags116,
		NULL,
		 chamberAnteroom,
		 chamberAnteroom,
		 "The door is open.\n",
		"You see",
		 "You walk through the door into the chamber anteroom\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		 toggleLibaryDoor,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 117 = closedDoorToAnteroom */
		alwaysTrue,
		 "An ornate wooden door to the west leading to the chamber anteroom. It's open",
		tags117,
		 library,
		NULL,
		 chamberAnteroom,
		 "The door is closed.\n",
		"You see",
		 "The door is closed.\n",
		99,
		9999,
		0,
		0,
		 toggleLibaryDoor,
		 isAlreadyClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 118 = openDoorToBackroom */
		alwaysTrue,
		 "an open door to the south",
		tags118,
		NULL,
		 backroom,
		 backroom,
		 "The door is open.\n",
		"You see",
		 "You walk through the door into the backroom.\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		 toggleLibaryDoor,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 119 = closedDoorToBackroom */
		alwaysTrue,
		 "a closed door to the south",
		tags119,
		 cave,
		NULL,
		 backroom,
		 "The door is closed.\n",
		"You see",
		 "The door is closed.\n",
		99,
		9999,
		0,
		0,
		 toggleBackdoor,
		 isAlreadyClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 120 = openDoorToCave */
		alwaysTrue,
		 "an open door to the north",
		tags120,
		NULL,
		 cave,
		 cave,
		 "The door is open.\n",
		"You see",
		 "You walk through the door into the cave.\n",
		99,
		9999,
		0,
		0,
		 isAlreadyOpen,
		 toggleBackdoor,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 121 = closedDoorToCave */
		alwaysTrue,
		 "a closed door to the north",
		tags121,
		 backroom,
		NULL,
		 cave,
		 "The door is closed.\n",
		"You see",
		 "The door is closed.\n",
		99,
		9999,
		0,
		0,
		 toggleBackdoor,
		 isAlreadyClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 122 = openBox */
		alwaysTrue,
		 "a wooden box",
		tags122,
		NULL,
		NULL,
		NULL,
		 "The box is open.\n",
		"You see",
		"You can't get any closer than this.\n",
		 5,
		 10,
		0,
		0,
		 isAlreadyOpen,
		 toggleBox,
		 isStillOpen,
		 isAlreadyOpen,
		0
	},
	{	/* 123 = closedBox */
		alwaysTrue,
		 "a wooden box",
		tags123,
		NULL,
		NULL,
		NULL,
		 "The box is closed.\n",
		"You see",
		"You can't get any closer than this.\n",
		 5,
		9999,
		0,
		0,
		 toggleBox,
		 isAlreadyClosed,
		 toggleBoxLock,
		 isAlreadyUnlocked,
		0
	},
	{	/* 124 = lockedBox */
		alwaysTrue,
		 "a wooden box",
		tags124,
		 backroom,
		NULL,
		NULL,
		 "The box is closed.\n",
		"You see",
		"You can't get any closer than this.\n",
		 5,
		9999,
		0,
		0,
		 isStillLocked,
		 isAlreadyClosed,
		 isAlreadyLocked,
		 toggleBoxLock,
		0
	},
	{	/* 125 = openIronChest */
		alwaysTrue,
		 "an open iron chest",
		tags125,
		NULL,
		NULL,
		NULL,
		 "The chest is locked.\n",
		"You see",
		"You can't get any closer than this.\n",
		 5,
		 10,
		0,
		0,
		 isAlreadyOpen,
		 toggleIronChest,
		 isStillOpen,
		 isAlreadyOpen,
		0
	},
	{	/* 126 = closedIronChest */
		alwaysTrue,
		 "a closed iron chest",
		tags126,
		NULL,
		NULL,
		NULL,
		 "The chest is closed.\n",
		"You see",
		"You can't get any closer than this.\n",
		 5,
		9999,
		0,
		0,
		 toggleIronChest,
		 isAlreadyClosed,
		 toggleIronChestLock,
		 isAlreadyUnlocked,
		0
	},
	{	/* 127 = lockedIronChest */
		alwaysTrue,
		 "a locked iron chest",
		tags127,
		 wardensOffice,
		NULL,
		NULL,
		 "The chest is locked.\n",
		"You see",
		"You can't get any closer than this.\n",
		 5,
		9999,
		0,
		0,
		 isStillLocked,
		 isAlreadyClosed,
		 isAlreadyLocked,
		 toggleIronChestLock,
		0
	},
	{	/* 128 = keyForIronChest */
		alwaysTrue,
		 "a bloody iron key",
		tags128,
		 openStitchedCorpse,
		NULL,
		NULL,
		 "The key has been taken from inside a corpse.\n",
		"You see",
		"You can't get any closer than this.\n",
		 1,
		9999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 129 = keyForBox */
		alwaysTrue,
		 "a tiny key",
		tags129,
		 cave,
		NULL,
		NULL,
		 "The key is really small and shiny.\n",
		"You see",
		"You can't get any closer than this.\n",
		 1,
		9999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 130 = keyForSewerGate */
		alwaysTrue,
		 "a small key",
		tags130,
		 forbiddenCrypt,
		NULL,
		NULL,
		 "The key looks like it was dropped accidently \n",
		"You see",
		"You can't get any closer than this.\n",
		 1,
		9999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 131 = torch */
		alwaysTrue,
		 "an unlit torch",
		tags131,
		 centralVaults,
		NULL,
		NULL,
		 "The torch is unlit. Maybe I can find a way to light it up",
		"You see",
		"You can't get any closer than this.\n",
		 1,
		9999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		 1
	},
	{	/* 132 = cauldron */
		alwaysTrue,
		 "a bubbling cauldron",
		tags132,
		 witchesLair,
		NULL,
		NULL,
		 "The cauldron is bubbling with a fire underneath",
		"You see",
		"You can't get any closer than this.\n",
		 999,
		9999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 133 = closedStitchedCorpse */
		alwaysTrue,
		 "a corpse with it's chest recently stitched together",
		tags133,
		 bodyPit,
		NULL,
		NULL,
		 "The corpse appears to have had it's chest stiched back together recently. \n This is a fresh body\n",
		"You see",
		"You can't get any closer than this.\n",
		 999,
		9999,
		0,
		0,
		 toggleCorpse,
		 isAlreadyClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 134 = openStitchedCorpse */
		alwaysTrue,
		 "a corpse with it's chest ripped open",
		tags134,
		NULL,
		NULL,
		NULL,
		 "You've ripped open the chest of the corpse revealing the insides\n",
		"You see",
		"You can't get any closer than this.\n",
		 999,
		9999,
		0,
		0,
		 isAlreadyOpen,
		 toggleCorpse,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 135 = bookArsGoetia */
		alwaysTrue,
		 "the ars goetia, a grimoire book on demonology",
		tags135,
		 library,
		NULL,
		NULL,
		 "This book appears to be grimoire. \n",
		"You see",
		"You can't get any closer than this.\n",
		 1,
		9999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	},
	{	/* 136 = bookArsTheurgiaGoetia */
		alwaysTrue,
		 "the ars theurgia goetia, a grimoire book on demonology",
		tags136,
		 openIronChest,
		NULL,
		NULL,
		 "This is another grimoire on demons\n",
		"You see",
		"You can't get any closer than this.\n",
		 1,
		9999,
		0,
		0,
		cannotBeOpened,
		cannotBeClosed,
		cannotBeLocked,
		cannotBeUnlocked,
		0
	}
};
